// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260218062722_AddCurrentPlanDayToUser")]
    partial class AddCurrentPlanDayToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AllergyUser", b =>
                {
                    b.Property<Guid>("AllergiesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("AllergiesId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("user_allergies", (string)null);
                });

            modelBuilder.Entity("Domain.Entitites.Allergy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("allergies", (string)null);
                });

            modelBuilder.Entity("Domain.Entitites.DailyMeal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DayIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("MealId")
                        .HasColumnType("uuid");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WeeklyPlanId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MealId");

                    b.HasIndex("WeeklyPlanId");

                    b.ToTable("daily_meals", (string)null);
                });

            modelBuilder.Entity("Domain.Entitites.DailyMealProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DailyMealId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEaten")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ReplacementMealId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DailyMealId");

                    b.HasIndex("ReplacementMealId");

                    b.HasIndex("UserId");

                    b.ToTable("daily_meal_progress", (string)null);
                });

            modelBuilder.Entity("Domain.Entitites.Meal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("meals", (string)null);
                });

            modelBuilder.Entity("Domain.Entitites.MealProduct", b =>
                {
                    b.Property<Guid>("MealId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<float>("AmountInGrams")
                        .HasColumnType("real");

                    b.HasKey("MealId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("meal_products", (string)null);
                });

            modelBuilder.Entity("Domain.Entitites.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AllergyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AllergyId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Domain.Entitites.Substitution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("OriginalMealId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SubstituteMealId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OriginalMealId");

                    b.HasIndex("SubstituteMealId");

                    b.ToTable("substitutions", (string)null);
                });

            modelBuilder.Entity("Domain.Entitites.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActivityLevel")
                        .HasColumnType("text");

                    b.Property<int>("CurrentPlanDay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Goal")
                        .HasColumnType("text");

                    b.Property<float?>("Height")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("WeeklyPlanId")
                        .HasColumnType("uuid");

                    b.Property<float?>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("WeeklyPlanId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Domain.Entitites.WeeklyPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("weekly_plans", (string)null);
                });

            modelBuilder.Entity("AllergyUser", b =>
                {
                    b.HasOne("Domain.Entitites.Allergy", null)
                        .WithMany()
                        .HasForeignKey("AllergiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entitites.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entitites.DailyMeal", b =>
                {
                    b.HasOne("Domain.Entitites.Meal", "Meal")
                        .WithMany()
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entitites.WeeklyPlan", "WeeklyPlan")
                        .WithMany("DailyMeals")
                        .HasForeignKey("WeeklyPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meal");

                    b.Navigation("WeeklyPlan");
                });

            modelBuilder.Entity("Domain.Entitites.DailyMealProgress", b =>
                {
                    b.HasOne("Domain.Entitites.DailyMeal", "DailyMeal")
                        .WithMany("Progresses")
                        .HasForeignKey("DailyMealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entitites.Meal", "ReplacementMeal")
                        .WithMany()
                        .HasForeignKey("ReplacementMealId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entitites.User", "User")
                        .WithMany("MealProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyMeal");

                    b.Navigation("ReplacementMeal");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entitites.MealProduct", b =>
                {
                    b.HasOne("Domain.Entitites.Meal", "Meal")
                        .WithMany("Products")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entitites.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Meal");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Entitites.Product", b =>
                {
                    b.HasOne("Domain.Entitites.Allergy", "Allergy")
                        .WithMany()
                        .HasForeignKey("AllergyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("Domain.ValueObjects.Nutrition", "NutritionPer100g", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<float>("Calories")
                                .HasColumnType("real")
                                .HasColumnName("Calories");

                            b1.Property<float>("Carbs")
                                .HasColumnType("real")
                                .HasColumnName("Carbs");

                            b1.Property<float>("Fats")
                                .HasColumnType("real")
                                .HasColumnName("Fats");

                            b1.Property<float>("Proteins")
                                .HasColumnType("real")
                                .HasColumnName("Proteins");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.Navigation("Allergy");

                    b.Navigation("NutritionPer100g")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entitites.Substitution", b =>
                {
                    b.HasOne("Domain.Entitites.Meal", "OriginalMeal")
                        .WithMany()
                        .HasForeignKey("OriginalMealId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entitites.Meal", "SubstituteMeal")
                        .WithMany()
                        .HasForeignKey("SubstituteMealId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OriginalMeal");

                    b.Navigation("SubstituteMeal");
                });

            modelBuilder.Entity("Domain.Entitites.User", b =>
                {
                    b.HasOne("Domain.Entitites.WeeklyPlan", "WeeklyPlan")
                        .WithMany()
                        .HasForeignKey("WeeklyPlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("WeeklyPlan");
                });

            modelBuilder.Entity("Domain.Entitites.DailyMeal", b =>
                {
                    b.Navigation("Progresses");
                });

            modelBuilder.Entity("Domain.Entitites.Meal", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Domain.Entitites.User", b =>
                {
                    b.Navigation("MealProgresses");
                });

            modelBuilder.Entity("Domain.Entitites.WeeklyPlan", b =>
                {
                    b.Navigation("DailyMeals");
                });
#pragma warning restore 612, 618
        }
    }
}
